---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.ingress.certname }}
spec:
  secretName: {{ .Values.ingress.tlssecretname }}
  dnsNames:
  - {{ .Values.ingress.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.ingress.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
