apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.label }}
  labels:
    app: {{ .Values.app.label }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label }}
    spec:
{{ if .Values.image.private }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-acr-secret
{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
#       resources:
# {{ toYaml .Values.resources | indent 12 }}
#         env:
#           - name: ASPNETCORE_ENVIRONMENT
#             value: Development
#
# TODO
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   successThreshold: 1
        #   tcpSocket:
        #     port: 80
        #   timeoutSeconds: 1
        # resources:
        #   limits:
        #     memory: 128Mi
        #     cpu: 100m
        #   requests:
        #     memory: 64Mi          
        #     cpu: 10m
