---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.label }}
    tier: {{ .Values.app.tier }}
    component: {{ .Values.app.component }}
    service: {{ .Values.app.service }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: {{ .Values.app.label }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  type: {{ .Values.service.type }}
