namespace: bis
replicaCount: 1
app:
  label: demoapp
  tier: dev
  component: frontend
  service: demoapp
image:
  pullPolicy: IfNotPresent
  repository: biscr.azurecr.io/bis/bisdemo
  tag: latest
service:
  name: demoapp
  port: 80
  protocol: TCP
  targetport: 80
  type: ClusterIP
  sessionAffinity: None
ingress:
  name: demoapp
  domain: demoapp.dev.bbraun.cloud
  tlssecretname: demoapp-dev-bbraun-cloud-tls-secret
  certname: demoapp-dev-bbraun-cloud-tls-cert
