---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-bis
  namespace: bis
  labels:
    service: speedtest-bis
    app: speedtest-bis
    tier: prd
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: speedtest-bis
  template:
    metadata:
      labels:
        app: speedtest-bis
        tier: prd
        component: frontend
        service: speedtest-bis
    spec:
      # If you need to pull from onPrem docker registry
      # imagePullSecrets:
      # - name: bis-nexus
      containers:
      - name: speedtest-bis
        image: biscr.azurecr.io/bis/speedtest:0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi          
            cpu: 10m
